"use strict";
exports.__esModule = true;
var Circle_1 = require("./Circle");
var reactangle_1 = require("./reactangle");
var ObjCircle = new Circle_1.Circle(2);
ObjCircle.Myarea();
ObjCircle.display();
var objRect = new reactangle_1.Rectangle(4, 5);
objRect.Myarea();
objRect.display();
